spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: nide
      secret-key: nide
      oss:
        endpoint: nide
        bucket: nide

      sms:
        host: https://smsmsgs.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 1
        appcode: fdsagfafadfgad

  application:
    name: gulimall-third-party

server:
  port: 30000
